FROM debian:jessie

USER root

# Install basic packages
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -yq --no-install-recommends \
    git \
    curl \
    build-essential \
    && apt-get clean


RUN apt-get install --yes npm && \
  apt-get install --yes nodejs && \
  ln -s /usr/bin/nodejs /usr/bin/node && \
  npm install -g bower && \
  apt-get clean